name: CI
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'machine type'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - ubuntu-slim
          - windows-latest
          - windows-2025
          - windows-2022
          - windows-2019
          - windows-11-arm
          - macos-latest
          - macos-26
          - macos-15-intel
          - macos-15
          - macos-14
          - macos-13
      nixpkgs:
        description: 'nixpkgs repo link'
        type: string
        default: https://github.com/nixos/nixpkgs
      branch:
        description: 'branch to clone'
        type: string
        default: master

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - run: whoami
    - uses: cachix/install-nix-action@v31
    - name: install tools
      run: nix profile add github:nixos/nixpkgs/nixpkgs-unstable#{fish,git}
    - name: change shell to fish
      run: sudo chsh -s $(which fish) runner
    - name: clone nixpkgs
      run: git clone --branch ${{ inputs.branch }} --single-branch ${{ inputs.nixpkgs }}
    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1
      with:
        limit-access-to-actor: true
